# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 176)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_pdf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pdf.setGeometry(QtCore.QRect(9, 10, 75, 23))
        self.btn_pdf.setObjectName("btn_pdf")
        self.lbl_pdf = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pdf.setGeometry(QtCore.QRect(90, 13, 271, 16))
        self.lbl_pdf.setObjectName("lbl_pdf")
        self.cant_a_partir = QtWidgets.QSpinBox(self.centralwidget)
        self.cant_a_partir.setGeometry(QtCore.QRect(200, 70, 42, 22))
        self.cant_a_partir.setProperty("value", 1)
        self.cant_a_partir.setObjectName("cant_a_partir")
        self.lbl_cant_pag = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cant_pag.setGeometry(QtCore.QRect(90, 40, 21, 16))
        self.lbl_cant_pag.setObjectName("lbl_cant_pag")
        self.lbl_pag_a_recortar = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pag_a_recortar.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.lbl_pag_a_recortar.setObjectName("lbl_pag_a_recortar")
        self.lbl_a_partir = QtWidgets.QLabel(self.centralwidget)
        self.lbl_a_partir.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.lbl_a_partir.setObjectName("lbl_a_partir")
        self.cant_pag_a_recortar = QtWidgets.QSpinBox(self.centralwidget)
        self.cant_pag_a_recortar.setGeometry(QtCore.QRect(200, 100, 42, 22))
        self.cant_pag_a_recortar.setObjectName("cant_pag_a_recortar")
        self.btn_iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_iniciar.setGeometry(QtCore.QRect(270, 130, 81, 23))
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 40, 41, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dividir PDF"))
        self.btn_pdf.setText(_translate("MainWindow", "Cargar PDF"))
        self.lbl_pdf.setText(_translate("MainWindow", "Ubicación del pdf"))
        self.lbl_cant_pag.setText(_translate("MainWindow", "x"))
        self.lbl_pag_a_recortar.setText(_translate("MainWindow", "Páginas a recortar"))
        self.lbl_a_partir.setText(_translate("MainWindow", "A partir de cual página va a recortar"))
        self.btn_iniciar.setText(_translate("MainWindow", "Iniciar recorte"))
        self.label.setText(_translate("MainWindow", "El PDF contiene"))
        self.label_2.setText(_translate("MainWindow", "páginas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
